### ISSUE TITLE
Google maps and Places from cocoapods 

### ISSUE THREAD

**Issue by embassem** [poulpix/PXGoogleDirections#25]
i still cant add google maps and google places from cocoapods with the solution you provide 
i got this error
"
target has frameworks with conflicting names: googlemapsbase.framework, googlemaps.framework, and googlemapscore.framework.
"
from where you get your version of Google maps and why it is different  from pods version ?

**Comment by embassem** [comment]
could you make your dependance like google places
https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/c/3/2/GooglePlaces/2.1.1/GooglePlaces.podspec.json

**Comment by poulpix** [comment]
@embassem I may try to add the Google Maps SDKs as an explicit dependency of my Pod, but the last time I tried this I always got compile-time errors, and had to fall back to the current system with bundled SDKs.
I know it's far from perfect, but I still don't have any working workaround.

**Comment by poulpix** [comment]
Hi again,
Just tried again and got this error from Cocoapods:

> The 'Pods-PXGoogleDirectionsSample' target has transitive dependencies that include static binaries

This issue is a known limitation of Cocoapods tied to the fact that we're trying to mix static and dynamic frameworks. The Google Maps iOS SDK is currently provided as static frameworks. The issue is referenced here: https://github.com/CocoaPods/CocoaPods/issues/3267.

I'm afraid I don't have a way to fix this right now, at least until Google switches to dynamic frameworks...

**Comment by poulpix** [comment]
Now linked to #28.
