### ISSUE TITLE
Sample code not working after successful linking of frameworks.

### ISSUE THREAD

**Issue by gabhisekdev** [poulpix/PXGoogleDirections#36]
[Sample.zip](https://github.com/poulpix/PXGoogleDirections/files/935192/Sample.zip)
Hi, The attached sample code is not working even after successful pod installation and linking of frameworks. It still shows "linker command failed with exit code 1 (use -v to see invocation)
 ".

I have followed doc of repository and have made sure that all frameworks have been linked but still the problem persists. Please download the sample attached project.

**Comment by poulpix** [comment]
Hi @GABHISEKBUNTY, after looking at your attached project, I think this is simply because you haven't downloaded the whole repo, but only the sample project.

The sample project references the `PXGoogleDirections` pod in its `Podfile` using a relative `../` path, but in the archive you posted, there is no link between the sample project and the framework at the upper level: the sample project is alone, and as such, the `PXGoogleDirections` framework is missing.

I can think of two different solutions:

1. Download the whole repo, not just the sample project, and then open `Terminal`, `cd` into the sample project folder, and run a `pod install`. After you re-open the sample project, everything should compile in Xcode.
2. Keep the sample project as-is, but edit the `Podfile` and remove the `, path => '../'` part in it; then, issue a `pod install` just like in the instructions above. It should also compile in Xcode, by using the latest version of `PXGoogleDirections` available online.

Please tell me if this helped. Anyway, I'll close this issue in a few days. If you still have troubles with the steps described above, please get back in touch!
