### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by hpbl** [poulpix/PXGoogleDirections#43]
Hi, I installed PXGoogleDirections as a git submodule, it all went fine. I was able to build the two targets, but when I run my project I get:

```
dyld: Library not loaded: @rpath/PXGoogleDirections.framework/PXGoogleDirections
  Referenced from: /var/containers/Bundle/Application/7B330ACD-03B9-4B20-A853-59A5ABA3CF67/MaryDrive.app/MaryDrive
  Reason: image not found
```

Could anyone help me please?

**Comment by poulpix** [comment]
Hi @hpbl, I would love to help you although this issue is 6+ months old (sorry for the delay!).
Did you manage to make it work?
Otherwise the first thing I would suggest would be to check that the PXGoogleDirections framework is clearly visible in your project's settings in both the "Embedded Binaries" and "Linked Frameworks and Libraries" sections.
Tell me if this helped or not.

**Comment by hpbl** [comment]
Hello, I managed to get it to work, but it's been so long now that I don't remember how. Feel free to close this issue.

**Comment by poulpix** [comment]
Hi, thanks, closing the issue then :)
