### ISSUE TITLE
Building for Swift 3

### ISSUE THREAD

**Issue by siddrajput** [poulpix/PXGoogleDirections#45]
Hello,

I am building a project in Swift 3 which also uses Google Maps iOS SDK. I read that "Please use v1.3 if you are on Swift 3 and/or Xcode 8." I read "Compatibility with Google pods" section but my question is how to build PXGoogleDirections v1.3? 

Number 4 says "Update your Podfile to give instructions on how to build both your project and the PXGoogleDirections submodule: but where is v1.3 specified? Thanks.

**Comment by poulpix** [comment]
Hi @siddrajput, you're right to ask... Since you're not using the Podfile to specify which version of the framework you want, you need to request it in another way.

One solution I found would be to specify the branch you need when adding the git submodule. So, instead of this:

> git submodule add https://github.com/poulpix/PXGoogleDirections.git Frameworks/External/PXGoogleDirections

Use this:

> git submodule add -b some_branch https://github.com/poulpix/PXGoogleDirections.git Frameworks/External/PXGoogleDirections

where `some_branch` is the name of a branch in the PXGoogleDirections repo.

Unfortunately not all branches have the same name pattern (I made a few mistakes here...), but for V1.3 I guess you could try using the branch named `pr/35`.

I will update the `Readme` for the next version to add this kind of information to help other developers...

Hope this helped!
