### ISSUE TITLE
Multipoints Route

### ISSUE THREAD

**Issue by ruchiragile** [poulpix/PXGoogleDirections#5]
Hi,

Is there any way if we would like to draw a route for more than two points.
for example from location A to location B to location C to location D to location A.

I would like to create a driving GPS demo for such routes.

**Comment by poulpix** [comment]
Yes, this notion exists in the Google Maps Directions API, it's called waypoints.
`PXGoogleDirections` allows you to add 1 or more waypoints to your directions request, like this:

``` swift
    var wp = [PXLocation]()
    wp.append(PXLocation.NamedLocation("your waypoint location 1"))
    wp.append(PXLocation.CoordinateLocation(CLLocationCoordinate2DMake(waypoint2_lat, waypoint2_lng)))
    directionsAPI.waypoints = wp
```

If you also want the Directions API to optimize the waypoints order for you, add this:

``` swift
    directionsAPI.optimizeWaypoints = true
```

Otherwise the calculation will be made with respect to the user-specified order.

Also see this paragraph in the official API docs to see how things are handled behind the scenes: https://developers.google.com/maps/documentation/directions/intro#Waypoints

Good luck!
