### ISSUE TITLE
No such module 'Google Maps'

### ISSUE THREAD

**Issue by filangelos** [poulpix/PXGoogleDirections#9]
I have followed the section "In case of problems" provided in your description though I cannot build my project since a _No such module 'Google Maps'_ error shows up all the time!
![screen shot 2016-04-12 at 11 39 05 am](https://cloud.githubusercontent.com/assets/12871137/14454484/7eab1d5a-00a3-11e6-829f-c97253b69154.png)
![screen shot 2016-04-12 at 11 39 21 am](https://cloud.githubusercontent.com/assets/12871137/14454487/7ed9422a-00a3-11e6-81e7-d82b75c2ae2f.png)
![screen shot 2016-04-12 at 11 39 42 am](https://cloud.githubusercontent.com/assets/12871137/14454485/7ed86030-00a3-11e6-9e50-e3a4d4c9607a.png)
![screen shot 2016-04-12 at 11 41 05 am](https://cloud.githubusercontent.com/assets/12871137/14454486/7ed93712-00a3-11e6-868e-2a7d98c1d13c.png)

**Comment by poulpix** [comment]
Hi @filangel, sorry for the late reply.
This kind of problem is a mess to solve, because of the mixing of old Objective-C APIs and newer Swift frameworks.
I don't have enough time right now to investigate your issue so I'll keep it open, but still I'll try to give you one or two hints:

1.
From which project does your "Linked Frameworks and Libraries" screenshot comes from? Is it from your own project, or the Pods project?
Anyway, here's how the Sample project works (the `PXGoogleDirectionsSample` project, not the `Pods` one):
![capture d ecran 2016-06-20 a 18 24 14](https://cloud.githubusercontent.com/assets/6537116/16202010/3a034d4c-3714-11e6-9017-325ea713e8bb.png)
As you can see, there are more than only two items. Also, the `PXGoogleDirections.framework` is not directly referenced. Instead, the Pods framework bundles everything that is needed.
This might be the first explanation for your problem, so try to stick to that configuration and see if it solves anything.

2.
The `Pods` project layout from your last screenshot is also different from mine. Did you alter something after running Cocoapods updates? Here's how mine looks like (again, taken from the `PXGoogleDirectionsSample` project):
![capture d ecran 2016-06-20 a 18 26 52](https://cloud.githubusercontent.com/assets/6537116/16202114/975b037c-3714-11e6-985c-1854c7e56347.png)
As you can see, I don't have any `GoogleMaps.framework` or `GoogleMaps.bundle` files inside the `Frameworks` folder of my `Pods` project.
I don't see why this would really harm, but you could still try removing these two references and see how it goes...

Please tell me if you managed to work it out.
Regards

**Comment by filangelos** [comment]
Hi @poulpix, 
I did not managed to sort it out, the pods seem to be totally messed up.
I started a new project from scratch and I managed to integrate your framework successfully.

Thank you for your time!

**Comment by poulpix** [comment]
Hi @filangel, glad you were able to sort t out!
Would you mind sharing how you did it from scratch so I can fix the pod if needed?
Thanks!

**Comment by filangelos** [comment]
Hi @poulpix,
the usual way; create a new Xcode project, initialize a pod file, install PXGoogleDirections first and then any framework needed.
Regards!

**Comment by javatar01** [comment]
m
